name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/latex
        with:
          args: "-s InstallArch.tex -o InstallArch.pdf README.md" # gets appended to pandoc command
