name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/latex:2.9
      - uses: simoneruffini/ArchInstall@master
        with:
          args: "--standalone --output=README.md main.tex"
