name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker run --rm --volume "`../../`:/data" --user `id -u`:`id -g` pandoc/latex:2.6 -s -o out.md main.tex 
